name: Deploy to FTP

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          tools: composer

      - name: Run composer
        run: composer update

      - name: Run unit tests
        run: ./vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: System preparation
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq ftp-upload

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          tools: composer

      - name: Run composer
        run: composer update

      - name: Build zip file
        run: yes j | ./build.sh

      - name: Upload to FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIRECTORY: ${{ secrets.FTP_DIRECTORY }}
          RELEASE_NAME: jtl-connector-shopware5-$CONNECTOR_VERSION.zip
        run: |
          ftp-upload --host $FTP_SERVER --user $FTP_USER --dir $FTP_DIRECTORY --password $FTP_PASSWORD --passive ./*.zip